### ISSUE TITLE
missing STACAC gear codes in function "gear.str"

### ISSUE THREAD

**Issue by srdbadmin** [srdbadmin/gulf#2]
I extracted landings data for both American plaice and for UNSPECIFIED FLOUNDER, from both historical NAFO data and more recent ZIFF files.

I used the function "gear.str" to obtain the ALPHA gear code and description for all the gear codes in the data, but a few of them are missing (specifically STACAC codes 0, 9, 13, 23, 40, 43, 50, 60 and 66).

Of these, a few (13, 23, 40, 50 and 60) are identified in the SAS file "\\glfgfcr02\landings\nafo\sumnafo.sas", but not all.

Still unresolved gear codes are therefore 0, 9, 43 and 66.

####################################################
gg <- c(0,9,10,11,12,13,14,15,16,17,19,21,22,23,24,31,33,40,41,42,43,45,50,51,53,59,60,61,62,63,64,66,71,72,90,99)
data.frame(
			gear.stacac.code=gg,
			gear.alpha = gear.str(gg, input.coding="stacac", output.coding="alpha"),
			gear.desc = gear.str(gg, input.coding="stacac", output.coding="description")
			)
####################################################

**Comment by srdbadmin** [comment]
A slight modification to this issue. The above mixes NAFO and STACAC codes.

The only undefined NAFO code in the function is 51. Based on the SAS script, it should be assigned to "LLS" alpha code.

Undefinied STACAC codes are 0 and 43.

**Comment by TobieSurette** [comment]
Updated gear table within gear.str function to include additional STACAC gear codes. Some of these codes are region-specific and so may not apply to all regions. There are many gear types with missing ALPHA and NAFO codes. An output.coding option ("category") was added to describe broad gear classes (ie traps, trawls, seines, etc...).
