### ISSUE TITLE
historical NAFO landings, issue with 1984 text file

### ISSUE THREAD

**Issue by srdbadmin** [srdbadmin/gulf#3]
When loading the 1984 NAFO data, I get the following warning, which is not a big deal but has the unfortunate consequence to change some numeric value into factors:

read.fwf(file=file.path("H:/landings/nafo", "nafo84.dat"), widths=c(2,2,2,3,2,3,1,5,5,5,5,5,5,5,5,5,5,5,5,5))

Warning message:
In readLines(file, n = thisblock) :
  incomplete final line found on 'H:/landings/nafo/nafo84.dat'

The text file was modified to include a line break after the last record, but somehow the warning persists. I believe that it is due to the fact that the last line has 3 blank spaces but shouldn't.

**Comment by TobieSurette** [comment]
Issue seems to be resolved...executed the above command without any warnings
